# Generated by Django 3.0.3 on 2020-02-24 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('SV', 'Save'), ('LG', 'Logging'), ('DV', 'Delivery'), ('PD', 'Post Delivery Status'), ('RD', 'Report Generation')], max_length=2)),
                ('recipient', models.EmailField(max_length=254)),
                ('subject', models.TextField()),
                ('body', models.TextField()),
            ],
            options={
                'db_table': 'notification',
            },
        ),
    ]
