# Generated by Django 3.0.3 on 2020-02-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='has_send',
            field=models.BooleanField(default=False),
        ),
    ]
